name: Daily Problem Hunter

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  hunt-problems:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get our code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install tools
        run: |
          pip install praw
      
      - name: Run advanced problem finder
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: |
          python scripts/advanced_scraper.py
      
      - name: Mine comments for hidden problems
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: |
          python scripts/comment_miner.py
      
      - name: Run AI analyzer
        run: |
          python scripts/ai_analyzer.py
      
      - name: Save all results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Problem Hunter Bot"
          git add data/
          git commit -m "Hunted problems for $(date +'%Y-%m-%d')" || echo "No new problems"
          git push
